import { proxy } from 'valtio'

const state = proxy({
  // intro: true,
  // patio: false,
  // bar: false,
  // sotano: false,
  // sala: false,
  // entrada: true,
  color: '#EFBD48',
  isLogoTexture: true,
  isFullTexture: false,
  logoDecal: './threejs.png',
  fullDecal: './threejs.png',
  date: '',
  time: '',
  calendar: false,
  nombre: '',
  telefono: '',
  correo: '',
  area: 'terraza',
  mesa: '0',
  personas: 0,
  numeracion: [],
  reservacion: false,
  reservacionHecha: false,
  reservacionConfirmada: false,
  reservacionCancelada: false,
  reservacionError: false,
  reservacionMessage: '',
  reservacionData: {},
  reservaId: '',
  videoLoading: true,
  modelLoading: true,
  hover: '',
  click: {},
})

export default state
